apiVersion: v1
kind: Service
metadata:
  name: opsdesk
  namespace: opsdesk
  labels:
    app.kubernetes.io/name: opsdesk
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: opsdesk
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: opsdesk
    app.kubernetes.io/component: application
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
